user nobody;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Root directory for Symfony public files
        root /var/www/symfony/public;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        # Symfony application front controller
        location ~ ^/index\.php(/|$) {
            fastcgi_pass symfony_backend:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;

            # Prevents URIs that include the front controller
            internal;
        }

        # Return 404 for all other php files
        location ~ \.php$ {
            return 404;
        }

        # Cache & Logs
        error_log /var/log/nginx/symfony_error.log;
        access_log /var/log/nginx/symfony_access.log;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        # Handle errors
        error_page 404 /index.php;
        error_page 500 502 503 504 /index.php;
    }
}
